# Generated by Django 3.2.9 on 2021-11-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Quiz 01', max_length=200)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.level')),
            ],
        ),
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=5000)),
                ('answer', models.CharField(max_length=5000)),
                ('answerType', models.IntegerField()),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.screen'),
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=500)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.level')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.screen')),
            ],
        ),
    ]
