# Generated by Django 3.2.9 on 2021-11-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')]),
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='answerType',
            field=models.IntegerField(choices=[(1, 'Short Text'), (2, 'Paragraph'), (3, 'Check Box')]),
        ),
    ]
