# Generated by Django 3.2.9 on 2021-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_auto_20211114_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='timePeriod',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizitem',
            name='option1',
            field=models.CharField(max_length=100, null=-1),
            preserve_default=-1,
        ),
        migrations.AddField(
            model_name='quizitem',
            name='option2',
            field=models.CharField(max_length=100, null=-1),
            preserve_default=-1,
        ),
        migrations.AddField(
            model_name='quizitem',
            name='option3',
            field=models.CharField(max_length=100, null=-1),
            preserve_default=-1,
        ),
        migrations.AddField(
            model_name='quizitem',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
